import {getHexagramGuide as getGuide01to10} from '../data/hexagram-guides-01-10.js';
import {getHexagramGuide11to16} from '../data/hexagram-guides-11-16.js';
import {getHexagramGuide17to24} from '../data/hexagram-guides-17-24.js';
import {getHexagramGuide25to32} from '../data/hexagram-guides-25-32.js';
import {getHexagramGuide33to40} from '../data/hexagram-guides-33-40.js';
import {getHexagramGuide41to48} from '../data/hexagram-guides-41-48.js';

const getHexagramGuide=number=>getGuide01to10(number)||getHexagramGuide11to16(number)||getHexagramGuide17to24(number)||getHexagramGuide25to32(number)||getHexagramGuide33to40(number)||getHexagramGuide41to48(number);
const $=selector=>document.querySelector(selector);
const numberFrom=text=>{const match=String(text??'').match(/№\s*(\d+)/);return match?Number(match[1]):null};
const circled=['①','②','③','④','⑤','⑥'];
function ensureStyles(){if($('#hexagram-guide-styles'))return;const style=document.createElement('style');style.id='hexagram-guide-styles';style.textContent=`
.hexagram-guide{margin-top:.75rem}.guide-section{margin:1rem 0}.guide-section>h4{margin:.2rem 0 .55rem}.guide-short{font-weight:650;line-height:1.55}.guide-more,.guide-stage{margin:.55rem 0;border-top:1px solid rgba(148,163,184,.25);padding-top:.55rem}.guide-more summary,.guide-stage summary{cursor:pointer;font-weight:650}.guide-more p,.guide-stage p{margin:.55rem 0 0;line-height:1.6}.guide-flow{line-height:1.85;font-weight:700}.guide-stage summary{display:flex;gap:.45rem;align-items:flex-start}.guide-stage-number{font-weight:850;min-width:1.5rem}.guide-classics-marker{margin-top:1.1rem}
.knowledge-sections>details.knowledge-details>summary::after{content:'+'}.knowledge-sections>details.knowledge-details[open]>summary::after{content:'−'}
.details-body .guide-more>summary::after,.details-body .guide-stage>summary::after,.hexagram-guide .guide-more>summary::after,.hexagram-guide .guide-stage>summary::after{content:none!important}
`;document.head.appendChild(style)}
function details(text,label='Розгорнути пояснення'){const el=document.createElement('details');el.className='guide-more';const summary=document.createElement('summary');summary.textContent=label;const p=document.createElement('p');p.textContent=text;el.append(summary,p);return el}
function section(title,short,long){const el=document.createElement('section');el.className='guide-section';const h=document.createElement('h4');h.textContent=title;const p=document.createElement('p');p.className='guide-short';p.textContent=short;el.append(h,p,details(long));return el}
function developmentSection(items,title='Розвиток стану'){const el=document.createElement('section');el.className='guide-section';const h=document.createElement('h4');h.textContent=title;const flow=document.createElement('p');flow.className='guide-flow';flow.textContent=items.map((item,index)=>`${circled[index]} ${item[0]}`).join(' → ');el.append(h,flow);items.forEach((item,index)=>{const d=document.createElement('details');d.className='guide-stage';const s=document.createElement('summary');const n=document.createElement('span');n.className='guide-stage-number';n.textContent=circled[index];const t=document.createElement('span');t.textContent=item[0];const p=document.createElement('p');p.textContent=item[1];s.append(n,t);d.append(s,p);el.append(d)});return el}
function buildGuide(guide,{resulting=false}={}){const wrap=document.createElement('div');wrap.className='hexagram-guide';wrap.append(section(resulting?'Образ нового стану':'Образ',guide.image.short,guide.image.long),developmentSection(guide.development,resulting?'Розвиток нового стану':'Розвиток стану'),section(resulting?'Приклад нового стану':'Приклад',guide.example.short,guide.example.long),section('На що звернути увагу',guide.attention.short,guide.attention.long));return wrap}
function setPrimaryLegacy(hidden){const meaning=$('#primary-meaning'),cycle=$('#primary-cycle'),caution=$('#primary-caution');meaning?.classList.toggle('hidden',hidden);cycle?.classList.toggle('hidden',hidden);cycle?.previousElementSibling?.classList.toggle('hidden',hidden);caution?.classList.toggle('hidden',hidden);caution?.previousElementSibling?.classList.toggle('hidden',hidden)}
function setSecondaryLegacy(hidden){const meaning=$('#secondary-meaning'),cycle=$('#secondary-cycle');meaning?.classList.toggle('hidden',hidden);meaning?.previousElementSibling?.classList.toggle('hidden',hidden);cycle?.classList.toggle('hidden',hidden);cycle?.previousElementSibling?.classList.toggle('hidden',hidden)}
function renderPrimary(){const body=$('#primary-meaning')?.parentElement;if(!body)return;const number=numberFrom($('#primary-details-title')?.textContent);const guide=getHexagramGuide(number);const existing=body.querySelector('.hexagram-guide[data-role="primary"]');if(existing?.dataset.hexagram===String(number))return;existing?.remove();if(!guide){setPrimaryLegacy(false);return}setPrimaryLegacy(true);const wrap=buildGuide(guide);wrap.dataset.role='primary';wrap.dataset.hexagram=String(number);const classics=$('#primary-classics-details');if(classics){classics.classList.add('guide-classics-marker');body.insertBefore(wrap,classics)}else body.appendChild(wrap)}
function renderSecondary(){const body=$('#secondary-details .secondary-details-body');if(!body)return;const number=numberFrom($('#secondary-details-title')?.textContent);const guide=getHexagramGuide(number);const existing=body.querySelector('.hexagram-guide[data-role="secondary"]');if(existing?.dataset.hexagram===String(number))return;existing?.remove();if(!guide){setSecondaryLegacy(false);return}setSecondaryLegacy(true);const wrap=buildGuide(guide,{resulting:true});wrap.dataset.role='secondary';wrap.dataset.hexagram=String(number);const classics=$('#secondary-classics-details');if(classics){classics.classList.add('guide-classics-marker');body.insertBefore(wrap,classics)}else body.appendChild(wrap)}
function renderGuide(){ensureStyles();renderPrimary();renderSecondary()}
const target=$('#answer-result');if(target){let scheduled=false;const schedule=()=>{if(scheduled)return;scheduled=true;requestAnimationFrame(()=>{scheduled=false;renderGuide()})};new MutationObserver(schedule).observe(target,{subtree:true,childList:true,characterData:true});schedule()}
